############################################
###            Orders                    ###
############################################

### Get All orders by operator username
GET http://localhost:8080/wedelivery/api/orders/
Accept: application/json

### Get All orders by code with all volumes
GET http://localhost:8080/wedelivery/api/orders/497232379

### Get order by code with volume by id
GET http://localhost:8080/wedelivery/api/orders/1258464486/volume/1494305280
Accept: application/json

## Get All orders by client username
### Get All orders by client username
GET http://localhost:8080/wedelivery/api/orders/889846120
Accept: application/json

### Create A New order
POST http://localhost:8080/wedelivery/api/orders
Content-Type: application/json
Authorization: Bearer


{
  "items": [
  {
    "available": true,
    "description": "Sprite",
    "haveSensor": false,
    "id": 3,
    "image": "sprite.jpg",
    "name": "Sprite",
    "price": 1.5,
    "quantity": 1
  },
  {
    "available": true,
    "description": "Sumol",
    "haveSensor": false,
    "id": 6,
    "image": "sumol.jpg",
    "name": "Sumol",
    "price": 1.5,
    "quantity": 1
  }
  ],
  "totalPrice": 26
}


### Update order Value
PATCH http://localhost:8080/wedelivery/api/orders/964018722
Content-Type: application/json

{
  "state": "Delivered"
}

