### Get All clients
GET http://localhost:8080/wedelivery/api/client
Accept: application/json

### Create A New client
POST http://localhost:8080/wedelivery/api/client
Content-Type: application/json

{
  "email": "johndoe@mail.com",
  "name": "John Doe",
  "username": "john",
  "password": "jd",
  "courseCode": 1
}

### Get All Courses
GET http://localhost:8080/wedelivery/api/course
Accept: application/json

### Create A New Course
POST http://localhost:8080/wedelivery/api/course
Content-Type: application/json

{
  "course_code": "23",
  "name": "Curso das Fadas"
}

### Get a client
GET http://localhost:8080/wedelivery/api/client/Goncalo
Accept: application/json

### Get a client subjects
GET http://localhost:8080/wedelivery/api/client/Goncalo/subjects
Accept: application/json

