### Get All clients
GET http://localhost:8080/wedelivery/api/clients
Accept: application/json

### Create A New client
POST http://localhost:8080/wedelivery/api/clients
Content-Type: application/json

{
  "username": "john",
  "email": "johndoe@mail.com",
  "password": "jd",
  "name": "John Doe",
  "courseCode": 1,
  "nif": 444555666,
  "postalCode": "2565-834",
  "country": "PT",
  "city": "Leiria",
  "address": "Rua x"
}

### Create A New manager
POST http://localhost:8080/wedelivery/api/managers
Content-Type: application/json

{
  "email": "margarida@mail.com",
  "name": "Margarida",
  "username": "Margarida",
  "password": "password"
}

### Create A New manager
POST http://localhost:8080/wedelivery/api/operators
Content-Type: application/json

{
  "email": "ana@mail.com",
  "name": "Ana",
  "username": "Ana",
  "password": "password"
}

