### Get All clients
GET http://localhost:8080/wedelivery/api/orders/Goncalo
Accept: application/json

### Get All managers
GET http://localhost:8080/wedelivery/api/managers
Accept: application/json

### Get All operators
GET http://localhost:8080/wedelivery/api/operators
Accept: application/json

### Get All orders
GET http://localhost:8080/wedelivery/api/orders
Accept: application/json


### Create A New client
POST http://localhost:8080/wedelivery/api/clients
Content-Type: application/json

{
  "username": "john",
  "email": "johndoe@mail.com",
  "password": "jd",
  "name": "John Doe",
  "courseCode": 1,
  "nif": 444555666,
  "postalCode": "2565-834",
  "country": "PT",
  "city": "Leiria",
  "address": "Rua x"
}

### Create A New manager
POST http://localhost:8080/wedelivery/api/managers
Content-Type: application/json

{
  "email": "margarida@mail.com",
  "name": "Margarida",
  "username": "Margarida",
  "password": "password"
}

### Create A New manager
POST http://localhost:8080/wedelivery/api/operators
Content-Type: application/json

{
  "email": "ana@mail.com",
  "name": "Ana",
  "username": "Ana",
  "password": "password"
}

### Create A New order
POST http://localhost:8080/wedelivery/api/orders
Content-Type: application/json

{
  "code": 1930548778,
  "deliveryDate": "2024-10-20T23:02:22.383Z[UTC]",
  "purchaseDate": "2024-10-20T23:02:22.383Z[UTC]",
  "state": "Pending",
  "username": "Guilherme",
  "usernameOperator": "DinisRX"
}



### Get All products in a warehouse --> Funcionou
GET http://localhost:8080/wedelivery/api/clients/



### Get All orders by client username
GET http://localhost:8080/wedelivery/api/clients/Goncalo
Accept: application/json


### Get All orders by operator username
GET http://localhost:8080/wedelivery/api/orders/
Accept: application/json

### Get All orders by code with all volumes
GET http://localhost:8080/wedelivery/api/orders/1258464486

### Get order by code with volume by id
GET http://localhost:8080/wedelivery/api/orders/1258464486/volume/1494305280
Accept: application/json


### Update Sensor Value
PATCH http://localhost:8080/wedelivery/api/sensors/1
Content-Type: application/json

{
  "currentValue": 50
}

