############################################
###            Volume                    ###
############################################

### GET All Volumes
GET http://localhost:8080/wedelivery/api/volumes
Accept: application/json

### GET Volume ID
GET http://localhost:8080/wedelivery/api/volumes/232315818
Accept: application/json

### GET Volume Details
GET http://localhost:8080/wedelivery/api/volumes/232315818/details
Accept: application/json



