############################################
###            Products                  ###
############################################

### Get All warehouses --> Funcionou
GET http://localhost:8080/wedelivery/api/warehouses
Accept: application/json

### Get Warehouse by name --> Funcionou
GET http://localhost:8080/wedelivery/api/warehouses/Leiria
Accept: application/json

### Get All products in a warehouse --> Funcionou
GET http://localhost:8080/wedelivery/api/warehouses/Leiria/products

### Get product by Id and warehouse name
GET http://localhost:8080/wedelivery/api/warehouses/Leiria/products/1
Accept: application/json




