name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # Atualize para a versão do Node.js que você está usando

      - name: Install dependencies
        run: |
          cd wedelivery-client  # Mude para o diretório correto
          npm install

      - name: Run tests
        run: |
          cd wedelivery-client  # Mude para o diretório correto
          npm test

