name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Define a versão do JDK
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use a versão do Node.js que você está usando

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce

      - name: Build with Maven
        run: |
          cd wedelivery  # Mude para o diretório onde está o pom.xml
          mvn clean install  # Executa o comando Maven

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Pull Docker images with retry
        run: |
          cd wedelivery  # Mude para o diretório correto
          docker-compose up -d  # Inicia os serviços em segundo plano
          sleep 60
          for i in {1..5}; do
            docker-compose pull && break || sleep 10;
          done

      - name: Deploy application
        run: |
          cd wedelivery  # Mude para o diretório correto
          make deploy  # Executa o comando make deploy
          sleep 60

      - name: Install dependencies
        run: |
          cd wedelivery-client  # Mude para o diretório correto
          npm install  # Instala as dependências do cliente

      - name: Check if services are running
        run: |
          if ! docker ps | grep -q 'webserver'; then
            echo "Error: Docker service is not running!"
            exit 1
          fi

      - name: Run TypeScript compilation
        run: |
          cd wedelivery-client  # Mude para o diretório correto
          npx tsc --noEmit  # Executa a compilação TypeScript sem emitir arquivos

      - name: Start dev server and run tests
        run: |
          cd wedelivery-client  # Mude para o diretório correto
          echo "Starting dev server..."
          npm run dev &  # Inicia o servidor em segundo plano
          echo $! > dev_server.pid  # Armazena o PID do processo
          echo "Waiting for Cypress to run tests..."
          wait-on http://localhost:3000 && npx cypress run
          echo "Tests completed. Stopping dev server..."
          kill $(cat dev_server.pid)  # Encerra o servidor

      - name: Clean up
        run: |
          cd wedelivery  # Mude para o diretório correto
          docker-compose down  # Para parar os containers
