name: Markdown Lint

on:
  push:
    paths:
      - README.md  # Executa o workflow apenas quando README.md é alterado
  pull_request:
    paths:
      - README.md  # Executa o workflow em pull requests que alteram README.md

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli

      - name: Run markdownlint on README.md
        run: |
          markdownlint README.md